language: groovy
jdk:
- oraclejdk8
branches:
  only:
  - master
  - dev

before_install:
- export TZ=Australia/Canberra
- wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
- chmod +x ala_common.sh
- source ./ala_common.sh
- ala_travis_grails_setup_env
before_script:
- npm install
script:
- node_modules/karma/bin/karma start karma.conf.js --single-run --browsers PhantomJS
- grails clean; grails refresh-dependencies --non-interactive && grails test-app -clover.on :unit --non-interactive --stacktrace && ala_travis_grails_build

env:
  global:
  - secure: HQaT+1B5r/7A15V3QHs5Lw1S8jNWgjgCKa8Fz7aEF4F+FHBiTqqM/fvFWcC+g7KHkLhgTht2efEIp9akBt8sArz1xp/BGhKr4JJRGU2uYJE8NpFb08u1OPAvurWQ72bwihJQBJWI9VXiQGoGQffLQL1yLQmlGMFbU/sOLzUxhGQ=
  - secure: Dc3FdXwu0j+tKyETSmZmULlEmVpQ7yKk+74zauRfEts0IyH1gUEuFr2ODTNUUFrjNRR/yW2dc0erlCyUc/CAGdALVRFzImz45WUjs0VgBtH2MW6tkgLd4DhDTDUpxOZMKZBEK91UVqK/2C0811c3UbvDBbuGrNacW5PPdzYoS9o=
