os: linux
dist: bionic
language: groovy
jdk:
  - openjdk8
branches:
  only:
  - master
  - dev
  - grails3
  - grails4

before_install:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/node_modules
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - npm install

script:
  - node_modules/karma/bin/karma start karma.conf.js --single-run --browsers ChromeHeadless
  - ./gradlew check

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./gradlew clean && travis_retry ./gradlew publish'

env:
  global:
    - secure: HQaT+1B5r/7A15V3QHs5Lw1S8jNWgjgCKa8Fz7aEF4F+FHBiTqqM/fvFWcC+g7KHkLhgTht2efEIp9akBt8sArz1xp/BGhKr4JJRGU2uYJE8NpFb08u1OPAvurWQ72bwihJQBJWI9VXiQGoGQffLQL1yLQmlGMFbU/sOLzUxhGQ=
    - secure: Dc3FdXwu0j+tKyETSmZmULlEmVpQ7yKk+74zauRfEts0IyH1gUEuFr2ODTNUUFrjNRR/yW2dc0erlCyUc/CAGdALVRFzImz45WUjs0VgBtH2MW6tkgLd4DhDTDUpxOZMKZBEK91UVqK/2C0811c3UbvDBbuGrNacW5PPdzYoS9o=
