---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.profile.hub
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf:
              - application/pdf
              - application/x-pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        upload:
            maxFileSize: 5000000
            maxRequestSize: 5000000
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
management:
    endpoints:
        jmx:
            unique-names: true

server:
    tomcat:
        port-header: 'X-Forwarded-Port'
        protocol-header: 'X-Forwarded-Proto'
        remote-ip-header: 'X-Forwarded-For'
---

grails:
    config:
        locations:
            - file:/data/profile-hub/config/profile-hub-config.properties
            - file:/data/profile-hub/config/profile-hub-config.yml
            - file:/data/profile-hub/config/profile-hub-config.groovy

---
security:
    cas:
        enabled: false
        adminRole: 'ROLE_ADMIN'
        uriExclusionFilterPattern:
            - '/assets/.*'
            - '/openapi/.*'
            - '/webjars/.*'
        uriFilterPattern:
        authenticateOnlyIfCookieFilterPattern: '*'
        authenticateOnlyIfLoggedInFilterPattern:
    oidc:
        enabled: true
        discoveryUri: https://auth.ala.org.au/cas/oidc/.well-known
        scope: "openid,profile,email,ala,roles"
        clientId: some-client-id
        secret: some-client-secret
        allowUnsignedIdTokens: true
    jwt:
        enabled: true
        discoveryUri: https://auth.ala.org.au/cas/oidc/.well-known
        fallbackToLegacyBehaviour: true

---

webservice:
    jwt: true
    jwt-include-legacy-headers: true
    jwt-scopes: "openid profile email ala roles profile-service/write users/read"

---
biocache:
    wms:
        layer: 'ALA:occurrences'

app:
    http:
        header:
            userName: "X-ALA-userName"
    analytics:
        apiid: cd1
        userid: cd2
        collectionid: cd3
        profileid: cd4

---

openapi:
    title: Profiles APIs
    description: APIs to query a collection in profiles
    terms: https://www.ala.org.au/terms
    contact:
        name: Support
        email: support@ala.org.au
    license:
        name: Mozilla Public License 1.1
        url: https://www.mozilla.org/en-US/MPL/1.1/
    version: '@info.app.version@'
    cachetimeoutms: 0
    components:
        security:
            oauth2:
                baseUrl: https://auth.ala.org.au/cas/oidc